version: "3.8"
services:

  # APPLICATION SERVICE
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: alpine-nginx-php-fpm
    container_name: "laravel-application"
    restart: unless-stopped
    ports:
      - "8000:80"
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - laravel

  # DATABASE SERVICE
  database:
    image: mysql:latest
    container_name: "mysql-database"
    restart: unless-stopped
    ports:
      - "8336:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
